# Generated by Django 5.0.4 on 2025-06-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_title', models.CharField(max_length=255)),
                ('released_year', models.IntegerField()),
                ('runtime', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('overview', models.TextField()),
                ('director', models.CharField(max_length=100)),
                ('star1', models.CharField(max_length=100)),
                ('star2', models.CharField(max_length=100)),
            ],
        ),
    ]
