# Generated by Django 5.1.1 on 2025-06-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_searchhistory_options_searchhistory_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='certificate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='gross',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='meta_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='no_of_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='movie',
            name='star3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='star4',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
