services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Django server
      - "8888:8888"  # Jupyter Notebook
    volumes:
      - .:/app
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_DEBUG=True
      - NEO4J_URI=bolt://neo4j:7687
    depends_on:
      - neo4j
      - redis
    tty: true
    stdin_open: true
  neo4j:
    image: neo4j:5.26
    ports:
      - "7474:7474"  # Neo4j Browser
      - "7687:7687"  # Neo4j Bolt
    environment:
      - NEO4J_AUTH=none
    volumes:
      - neo4j_data:/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
volumes:
  neo4j_data: