services:
  web:
    build: .
    command: /app/entrypoint.sh
    volumes:
      - .:/app
      - search_indices:/app/search_indices
    ports:
      - "8000:8000"
    depends_on:
      - db
      - neo4j
      - redis
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/dbname
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SEARCH_INDEX_PATH=/app/search_indices

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dbname

  neo4j:
    image: neo4j:latest
    volumes:
      - neo4j_data:/data
    ports:
      - "7474:7474"  # HTTP port for Neo4j Browser
      - "7687:7687"  # Bolt port for application
    environment:
      - NEO4J_AUTH=neo4j/password

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  neo4j_data:
  redis_data:
  search_indices: