# Generated by Django 4.2.16 on 2025-06-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_title', models.CharField(max_length=255)),
                ('released_year', models.CharField(max_length=4)),
                ('certificate', models.CharField(blank=True, max_length=10)),
                ('runtime', models.CharField(blank=True, max_length=20)),
                ('genre', models.CharField(max_length=100)),
                ('imdb_rating', models.FloatField()),
                ('overview', models.TextField()),
                ('meta_score', models.FloatField(blank=True, null=True)),
                ('director', models.CharField(max_length=100)),
                ('star1', models.CharField(max_length=100)),
                ('star2', models.CharField(max_length=100)),
                ('star3', models.CharField(max_length=100)),
                ('star4', models.CharField(max_length=100)),
                ('no_of_votes', models.IntegerField()),
                ('gross', models.BigIntegerField(blank=True, null=True)),
                ('embedding', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
